syscallheader = open("syscalls.h").readlines()
osprogramtemplate = open("Programs/osprogram.h.template").read()
osprogramout = open("Programs/osprogram.h", "w")

header = """
/*
 ***************************************************************
 * This file is autogenerated. Modifications to its contents   *
 * will not be persistent. Modify the template source instead. *
 ***************************************************************
 */ 
"""

templatesymbol = "<~syscall_decls~>"

extdecls = ""

for line in syscallheader:
    if ("attribute" in line):
        extdecls += (" " + line + " ")
    if ("sys_" in line and "inline" in line):
        extdecls += ( "extern " + line.replace("\n", "").replace("\r", "") + ";\n" )

osprogramout.write(header + osprogramtemplate.replace(templatesymbol, extdecls))

osprogramout.close()
