
/*
 ***************************************************************
 * This file is autogenerated. Modifications to its contents   *
 * will not be persistent. Modify the template source instead. *
 ***************************************************************
 */ 
/*
 * syscall_numbers.h
 *
 *  Created on: Mar 18, 2015
 *      Author: Kevin
 */

#ifndef SYSCALL_NUMBERS_H_
#define SYSCALL_NUMBERS_H_

#define SYSCALL_EXIT          	(0)
#define SYSCALL_YIELD         	(1)
#define SYSCALL_SLEEP         	(2)
#define SYSCALL_SPAWN         	(3)
#define SYSCALL_SPAWN2        	(4)
#define SYSCALL_FORK          	(5)
#define SYSCALL_RESET         	(6)
#define SYSCALL_WAIT          	(7)
#define SYSCALL_KILL          	(8)
#define SYSCALL_GET_TID       	(9)
#define SYSCALL_SET_PRI       	(10)
#define SYSCALL_GET_PRI       	(11)
#define SYSCALL_LOCK          	(12)
#define SYSCALL_UNLOCK        	(13)
#define SYSCALL_PUTS          	(14)
#define SYSCALL_PUTC          	(15)
#define SYSCALL_WRITE         	(16)
#define SYSCALL_READ          	(17)
#define SYSCALL_SEEK          	(18)
#define SYSCALL_IOCTL         	(19)
#define SYSCALL_CLOSE         	(20)
#define SYSCALL_OPEN          	(21)
#define SYSCALL_LISTDIR       	(22)
#define SYSCALL_RWDIR         	(23)
#define SYSCALL_CHDIR         	(24)
#define SYSCALL_MKDIR         	(25)
#define SYSCALL_UNLINK        	(26)
#define SYSCALL_MV            	(27)
#define SYSCALL_CP            	(28)
#define SYSCALL_MOUNT         	(29)
#define SYSCALL_UNMOUNT       	(30)
#define SYSCALL_POPEN         	(31)
#define SYSCALL_DOPEN         	(32)
#define SYSCALL_FLUBBER       	(33)
#define SYSCALL_SET_PORT_DIRS 	(34)
#define SYSCALL_READ_PORT     	(35)
#define SYSCALL_WRITE_PORT    	(36)

#endif /* SYSCALL_NUMBERS_H_ */
