
/*
 ***************************************************************
 * This file is autogenerated. Modifications to its contents   *
 * will not be persistent. Modify the template source instead. *
 ***************************************************************
 */ 
/*
 * syscall_numbers.h
 *
 *  Created on: Mar 18, 2015
 *      Author: Kevin
 */

#ifndef SYSCALL_NUMBERS_H_
#define SYSCALL_NUMBERS_H_

#define SYSCALL_EXIT          	(0)
#define SYSCALL_YIELD         	(1)
#define SYSCALL_SLEEP         	(2)
#define SYSCALL_SPAWN         	(3)
#define SYSCALL_FORK          	(4)
#define SYSCALL_RESET         	(5)
#define SYSCALL_WAIT          	(6)
#define SYSCALL_KILL          	(7)
#define SYSCALL_GET_TID       	(8)
#define SYSCALL_SET_PRI       	(9)
#define SYSCALL_GET_PRI       	(10)
#define SYSCALL_LOCK          	(11)
#define SYSCALL_UNLOCK        	(12)
#define SYSCALL_PUTS          	(13)
#define SYSCALL_PUTC          	(14)
#define SYSCALL_WRITE         	(15)
#define SYSCALL_READ          	(16)
#define SYSCALL_SEEK          	(17)
#define SYSCALL_IOCTL         	(18)
#define SYSCALL_CLOSE         	(19)
#define SYSCALL_OPEN          	(20)
#define SYSCALL_LISTDIR       	(21)
#define SYSCALL_RWDIR         	(22)
#define SYSCALL_CHDIR         	(23)
#define SYSCALL_MKDIR         	(24)
#define SYSCALL_UNLINK        	(25)
#define SYSCALL_MV            	(26)
#define SYSCALL_CP            	(27)
#define SYSCALL_MOUNT         	(28)
#define SYSCALL_UNMOUNT       	(29)
#define SYSCALL_POPEN         	(30)
#define SYSCALL_DOPEN         	(31)
#define SYSCALL_FLUBBER       	(32)
#define SYSCALL_SET_PORT_DIRS 	(33)
#define SYSCALL_READ_PORT     	(34)
#define SYSCALL_WRITE_PORT    	(35)

#endif /* SYSCALL_NUMBERS_H_ */
